# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 14:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import durationfield.db.models.fields.duration


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index', models.IntegerField(help_text=b'Position in the response list.')),
                ('body', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text=b'Enter your question here.')),
                ('question_type', models.CharField(choices=[(b'text', b'text'), (b'radio', b'radio'), (b'select', b'dropdown'), (b'checkbox', b'Select Multiple'), (b'integer', b'integer')], default=b'text', help_text=b'Choose the type of answser.', max_length=9)),
                ('has_other', models.BooleanField(default=False, help_text=b"If checked, allow user to enter a personnal choice. (Don't forget to add an 'Other' choice at the end of your list of choices)")),
                ('choices', models.TextField(blank=True, help_text=b'Enter choices here separated by a new line. (Only for radio and select multiple)', null=True)),
                ('order', models.IntegerField()),
                ('correct_answer', models.TextField(blank=True, help_text=b'Enter correct answser(s) here separated by a new line.', null=True)),
                ('required', models.BooleanField(default=True, help_text=b'If checked, an answer is required')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_spent', durationfield.db.models.fields.duration.DurationField(default=0, help_text=b'Total recorded time to complete the survey')),
                ('is_frozen', models.BooleanField(default=False, help_text=b'When True, answers to that response cannot be updated.')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('title', models.CharField(help_text=b'Enter a survey title.', max_length=150)),
                ('description', models.TextField(blank=True, help_text=b'This desciption will be displayed for interviewee.', null=True)),
                ('published', models.BooleanField(default=False)),
                ('quizz_mode', models.BooleanField(default=False, help_text=b'If checked, correct answser are required')),
                ('defaults_single_page', models.BooleanField(default=False, help_text=b'If checked, will display all questions on a single page, else there will be one question per page.')),
                ('one_response_only', models.BooleanField(default=False, help_text=b'Only allows to answer survey once.')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyModel'),
        ),
        migrations.AddField(
            model_name='response',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.SurveyModel'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.Response'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([('question', 'response')]),
        ),
    ]
